<?php

namespace AML\ServiraceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TownRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TownRepository extends EntityRepository
{
}
