aml_servirace:
    resource: "@AMLServiraceBundle/Resources/config/routing.yml"
    prefix:   /

aml_user:
    resource: "@AMLUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
