aml_user_homepage:
    path:     /
    defaults: { _controller: AMLUserBundle:Default:index }

aml_user_hello:
    path:     /hello/{name}
    defaults: { _controller: AMLUserBundle:Default:helloName, name: 'Default NAME' }

aml_user_index:
    path:     /user/index
    defaults: { _controller: AMLUserBundle:User:index }

aml_user_index_select:
    path:     /user/index/{id}
    defaults: { _controller: AMLUserBundle:User:showUser, id: 1 }

aml_user_articles:
    path:     /user/articles/{page}
    defaults: { _controller: AMLUserBundle:User:articles, page: 1 }

aml_contact_add:
        path:     /contact/add
        defaults: { _controller: AMLUserBundle:Contact:add }

aml_contact_create:
    path:     /contact/create
    defaults: { _controller: AMLUserBundle:Contact:create }
    methods: POST

aml_user_add:
    path:     /user/add
    defaults: { _controller: AMLUserBundle:User:add }

aml_user_create:
    path:     /user/create
    defaults: { _controller: AMLUserBundle:User:create }
    methods: POST

aml_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AMLUserBundle:User:edit }

aml_user_view:
    path:     /user/view/{id}
    defaults: { _controller: AMLUserBundle:User:view }

aml_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: AMLUserBundle:User:delete }
