aml_user_homepage:
    path:     /
    defaults: { _controller: AMLUserBundle:Default:index, name: 'Default NAME' }

aml_blank_page:
    path:     /blank
    defaults: { _controller: AMLUserBundle:Default:blank}

aml_login_page:
    path:     /login
    defaults: { _controller: AMLUserBundle:Default:login}

aml_button_page:
    path:     /buttons
    defaults: { _controller: AMLUserBundle:Default:buttons}

aml_forms_page:
    path:     /forms
    defaults: { _controller: AMLUserBundle:Default:forms}

aml_tables_page:
    path:     /tables
    defaults: { _controller: AMLUserBundle:Default:tables}

aml_panels_page:
    path:     /panels
    defaults: { _controller: AMLUserBundle:Default:panels}

aml_notifications_page:
    path:     /notifications
    defaults: { _controller: AMLUserBundle:Default:notifications}

aml_typography_page:
    path:     /typographys
    defaults: { _controller: AMLUserBundle:Default:typographys}

aml_icons_page:
    path:     /icons
    defaults: { _controller: AMLUserBundle:Default:icons}

aml_grid_page:
    path:     /grids
    defaults: { _controller: AMLUserBundle:Default:grids}

aml_user_hello:
    path:     /hello/{name}
    defaults: { _controller: AMLUserBundle:Default:helloName, name: 'Default NAME' }

aml_user_index:
    path:     /user/index
    defaults: { _controller: AMLUserBundle:User:index }

aml_user_index_select:
    path:     /user/index/{id}
    defaults: { _controller: AMLUserBundle:User:showUser, id: 1 }

aml_user_articles:
    path:     /user/articles/{page}
    defaults: { _controller: AMLUserBundle:User:articles, page: 1 }

aml_contact_add:
        path:     /contact/add
        defaults: { _controller: AMLUserBundle:Contact:add }

aml_contact_create:
    path:     /contact/create
    defaults: { _controller: AMLUserBundle:Contact:create }
    methods: POST

aml_user_add:
    path:     /user/add
    defaults: { _controller: AMLUserBundle:User:add }

aml_user_create:
    path:     /user/create
    defaults: { _controller: AMLUserBundle:User:create }
    methods: POST

aml_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AMLUserBundle:User:edit }

aml_user_view:
    path:     /user/view/{id}
    defaults: { _controller: AMLUserBundle:User:view }

aml_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: AMLUserBundle:User:delete }
