aml_user_homepage:
    path:     /
    defaults: { _controller: AMLUserBundle:Default:index }

aml_user_hello:
    path:     /hello/{name}
    defaults: { _controller: AMLUserBundle:Default:helloName }

aml_user_index:
    path:     /user/index
    defaults: { _controller: AMLUserBundle:User:index }

aml_user_index_select:
    path:     /user/index/{id}
    defaults: { _controller: AMLUserBundle:User:showUser }

aml_user_articles:
    path:     /user/articles/{page}
    defaults: { _controller: AMLUserBundle:User:articles, page: 1 }
